import random as ran

def random_mob():
    shulker_colors = [
        'red', 'orange', 'yellow', 'green', 'blue', 'light_blue', 'purple', 'pink',
        'brown', 'black', 'white', 'light_gray', 'cyan', 'magenta', 'lime', 'gray',
        'default']

    sheep_colors = [
        'red', 'orange', 'yellow', 'green', 'blue', 'light_blue', 'purple', 'pink',
        'brown', 'black', 'white', 'light_gray', 'cyan', 'magenta', 'lime', 'gray',
        'jeb_']

    villager_biomes = ['plains', 'desert', 'savanna', 'taiga', 'snow', 'swamp', 'jungle']

    cats = ['black', 'british', 'calico', 'jellie', 'persian', 'ragdoll', 'red', 'siamese', 'tabby', 'tuxedo', 'white']
    wolves = ['ashen', 'black', 'chestnut', 'pale', 'rusty', 'snowy', 'spotted', 'striped', 'woods']

    horse_markings = ['black_dots','none','white_dots','white_details','white_fields']
    horse_bases=['white','creamy','chestnut','brown','black','gray','dark_brown']

    panda_types = ['brown','lazy','playful','worried','weak','aggressive','normal']

    rabbit_breeds = ['black','brown','desert','salt','splotched','toast','white']

    axolotl_variants = ['lucy', 'wild', 'gold', 'cyan', 'blue']

    tropical_fish_variants = ['anemone', 'black_tang', 'blue_dory', 'butterfly_fish', 'cichli', 'clownfish', 'cotton_candy_betta', 'dottyback', 'emperor_red_snapper', 'goatfish', 'moorish_idol', 'ornate_butterfly', 'parrotfish', 'queen_angel_fish',
    'red_cichlid', 'red_lipped_blenny', 'red_snapper', 'threadfin', 'tomato_clown', 'triggerfish', 'yellow_tang', 'yellowtail_parrot']

    climates = ['cold', 'warm', 'temperate']

    mobs = [
        'allay',
        'axolotl',
        'armadillo',
        'bat',
        'bee',
        'blaze',
        'bogged',
        'breeze',
        'camel',
        'cat',
        'cave_spider',
        'chicken',
        'cod',
        'cow',
        'creaking',
        'creeper',
        'dolphin',
        'donkey',
        'drowned',
        'elder_guardian',
        'ender_dragon',
        'enderman',
        'endermite',
        'evoker',
        'fox',
        'frog',
        'ghast',
        'glow_squid',
        'goat',
        'guardian',
        'hoglin',
        'horse',
        'husk',
        'iron_golem',
        'llama',
        'magma_cube',
        'mooshroom',
        'mule',
        'ocelot',
        'panda',
        'parrot',
        'phantom',
        'pig',
        'piglin',
        'piglin_brute',
        'pillager',
        'player',
        'polar_bear',
        'pufferfish',
        'rabbit',
        'ravager',
        'salmon',
        'sheep',
        'shulker',
        'silverfish',
        'skeleton',
        'skeleton_horse',
        'slime',
        'snow_golem',
        'sniffer',
        'spider',
        'squid',
        'stray',
        'strider',
        'tadpole',
        'trader_llama',
        'tropical_fish',
        'turtle',
        'vex',
        'villager',
        'vindicator',
        'wandering_trader',
        'warden',
        'witch',
        'wither',
        'wither_skeleton',
        'wolf',
        'zoglin',
        'zombie',
        'zombie_horse',
        'zombie_pigman',
        'zombie_villager'
    ]

    mob_metadata = {
        'allay': ['minecraft:allay[]'],
        'axolotl': [f'minecraft:axolotl[age={ran.choice(['adult','baby'])},variant={ran.choice(axolotl_variants)}]'],
        'armadillo': ['minecraft:armadillo[age=adult]', 'minecraft:armadillo[age=baby]'],
        'bat': ['minecraft:bat[]'],
        'bee': ['minecraft:bee[]'],
        'blaze': ['minecraft:blaze[]'],
        'bogged': ['minecraft:bogged[sheared=false]', 'minecraft:bogged[sheared=true]'],
        'breeze': ['minecraft:breeze[]'],
        'camel': ['minecraft:camel[age=adult]', 'minecraft:camel[age=baby]'],
        'cat': [f'minecraft:cat[age={ran.choice(['adult','baby'])},tame={ran.choice(['true','false'])},breed={ran.choice(cats)}]'],
        'cave_spider': ['minecraft:cave_spider[]'],
        'chicken': [f'minecraft:chicken[age={ran.choice(['adult','baby'])},climate={ran.choice(climates)}]'],
        'cod': ['minecraft:cod[]'],
        'cow': [f'minecraft:cow[age={ran.choice(['adult','baby'])},climate={ran.choice(climates)}]'],
        'creaking': ['minecraft:creaking[]'],
        'creeper': ['minecraft:creeper[charged=false]', 'minecraft:creeper[charged=true]'],
        'dolphin': [f'minecraft:dolphin[age={ran.choice(['adult','baby'])}]'],
        'donkey': ['minecraft:donkey[age=adult]', 'minecraft:donkey[age=baby]'],
        'drowned': ['minecraft:drowned[age=adult]', 'minecraft:drowned[age=baby]'],
        'elder_guardian': ['minecraft:elder_guardian[]'],
        'ender_dragon': ['minecraft:ender_dragon[]'],
        'enderman': ['minecraft:enderman[]'],
        'endermite': ['minecraft:endermite[]'],
        'evoker': ['minecraft:evocation_illager[]'],
        'fox': [f'minecraft:fox[age={ran.choice(['adult','baby'])},variant={ran.choice(['red','arctic'])}]'],
        'frog': [f'minecraft:frog[variant={ran.choice(['temperate','jungle'])}]'],
        'ghast': ['minecraft:ghast[]'],
        'glow_squid': ['minecraft:glow_squid[age=adult]', 'minecraft:glow_squid[age=baby]'],
        'goat': ['minecraft:goat[age=adult,variant=normal]', 'minecraft:goat[age=baby,variant=normal]', 'minecraft:goat[age=adult,variant=screamer]', 'minecraft:goat[age=baby,variant=screamer]'],
        'guardian': ['minecraft:guardian[]'],
        'hoglin': ['minecraft:hoglin[age=adult]', 'minecraft:hoglin[age=baby]'],
        'horse': [f'minecraft:horse[age={ran.choice(['adult','baby'])},base={ran.choice(horse_bases)},markings={ran.choice(horse_markings)}]'],
        'husk': ['minecraft:husk[age=adult]', 'minecraft:husk[age=baby]'],
        'iron_golem': ['minecraft:iron_golem[]'],
        'llama': [f'minecraft:llama[age={ran.choice(['adult','baby'])},color={ran.choice(['white','brown','gray','cream'])}]'],
        'magma_cube': ['minecraft:magma_cube[size=small]', 'minecraft:magma_cube[size=medium]', 'minecraft:magma_cube[size=large]'],
        'mooshroom': [f'minecraft:mooshroom[age={ran.choice(['adult','baby'])},mushroom={ran.choice(['red','brown'])}]'],
        'mule': ['minecraft:mule[age=adult]', 'minecraft:mule[age=baby]'],
        'ocelot': ['minecraft:ocelot[age=adult]', 'minecraft:ocelot[age=baby]'],
        'panda': [f'minecraft:panda[age={ran.choice(['adult','baby'])},personality={ran.choice(panda_types)}]'],
        'parrot': [f'minecraft:parrot[breed={ran.choice(['red','blue','green','cyan','silver'])}]'],
        'phantom': ['minecraft:phantom[]'],
        'pig': [f'minecraft:pig[age={ran.choice(['adult','baby'])},climate={ran.choice(climates)}]'],
        'piglin':['minecraft:piglin[age=adult]', 'minecraft:piglin[age=baby]'],
        'piglin_brute': ['minecraft:piglin_brute[]'],
        'pillager': ['minecraft:pillager[]'],
        'player': ['minecraft:player[]'],
        'polar_bear': ['minecraft:polar_bear[age=adult]', 'minecraft:polar_bear[age=baby]'],
        'pufferfish': ['minecraft:pufferfish[]'],
        'rabbit': [f'minecraft:rabbit[age={ran.choice(['adult','baby'])},variant={ran.choice(rabbit_breeds)}]'],
        'ravager': ['minecraft:ravager[]'],
        'salmon': ['minecraft:salmon[size=small]', 'minecraft:salmon[size=medium]', 'minecraft:salmon[size=large]'],
        'sheep': [f'minecraft:sheep[age={ran.choice(['adult','baby','sheared_adult'])},color={ran.choice(sheep_colors)}]'],
        'shulker': [f'minecraft:shulker=[color={ran.choice(shulker_colors)}]'],
        'silverfish': ['minecraft:silverfish[]'],
        'skeleton': ['minecraft:skeleton[]'],
        'skeleton_horse': ['minecraft:skeleton_horse[age=adult]', 'minecraft:skeleton_horse[age=baby]'],
        'slime': ['minecraft:slime[size=small]', 'minecraft:slime[size=medium]', 'minecraft:slime[size=large]'],
        'snow_golem': ['minecraft:snow_golem[]'],
        'sniffer': ['minecraft:sniffer[age=adult]', 'minecraft:sniffer[age=baby]'],
        'spider': ['minecraft:spider[]'],
        'squid': ['minecraft:squid[age=adult]', 'minecraft:squid[age=baby]'],
        'stray': ['minecraft:stray[]'],
        'strider': ['minecraft:strider[age=adult]', 'minecraft:strider[age=baby]'],
        'tadpole': ['minecraft:tadpole[]'],
        'trader_llama': [f'minecraft:trader_llama[age={ran.choice(['adult','baby'])},color={ran.choice(['white','brown','gray','cream'])}]'],
        'tropical_fish': [f'minecraft:tropical_fish[species={ran.choice(tropical_fish_variants)}]'],
        'turtle': ['minecraft:turtle[age=adult]', 'minecraft:turtle[age=baby]'],
        'vex': ['minecraft:vex[]'],
        'villager': [f'minecraft:villager_v2[age={ran.choice(['adult','baby'])},biome={ran.choice(villager_biomes)}]'],
        'vindicator': ['minecraft:vindicator[]'],
        'wandering_trader': ['minecraft:wandering_trader[]'],
        'warden': ['minecraft:warden[]'],
        'witch': ['minecraft:witch[]'],
        'wither': ['minecraft:wither[]'],
        'wither_skeleton': ['minecraft:wither_skeleton[]'],
        'wolf': [f'minecraft:wolf[age={ran.choice(['adult','baby'])},tame={ran.choice(['true','false'])},breed={ran.choice(wolves)}]'],
        'zoglin': ['minecraft:zoglin[age=adult]', 'minecraft:zoglin[age=baby]'],
        'zombie': ['minecraft:zombie[age=adult]', 'minecraft:zombie[age=baby]'],
        'zombie_horse': ['minecraft:zombie_horse[age=adult]', 'minecraft:zombie_horse[age=baby]'],
        'zombie_pigman': ['minecraft:zombie_pigman[age=adult]', 'minecraft:zombie_pigman[age=baby]'],
        'zombie_villager': [f'minecraft:zombie_villager_v2[age={ran.choice(['adult','baby'])},biome={ran.choice(villager_biomes)}]']
    }

    return (mob_metadata[ran.choice(mobs)])